In [38]:
#actividad 1: 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
df_2021 = pd.read_csv("df_2021_new.csv")
df_2021

/var/folders/xx/8ljg54gs66gdzlm3grgkg2vr0000gn/T/ipykernel_1436/3330143858.py:1: DtypeWarning: Columns (25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv("df_2021_new.csv")

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,EDAD_ALU,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,COD_RAMA,COD_MEN,ENS,DVR
0,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,54,15,15101,ARICA,410,41001,400,0,13,8
1,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,24,15,15101,ARICA,410,41001,400,0,13,1
2,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,51,15,15101,ARICA,410,41001,400,0,13,6
3,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,43,1,1101,IQUIQUE,410,41001,400,0,13,8
4,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,25,15,15101,ARICA,410,41001,400,0,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626451,2021,41899,4,COLEGIO SAN JORGE,8,BBIO,83,8304,LAJA,82,...,17,8,8304,LAJA,0,0,0,0,7,9
3626452,2021,41899,4,COLEGIO SAN JORGE,8,BBIO,83,8304,LAJA,82,...,17,8,8304,LAJA,0,0,0,0,7,6
3626453,2021,41899,4,COLEGIO SAN JORGE,8,BBIO,83,8304,LAJA,82,...,17,8,8304,LAJA,0,0,0,0,7,8
3626454,2021,41899,4,COLEGIO SAN JORGE,8,BBIO,83,8304,LAJA,82,...,17,8,8304,LAJA,0,0,0,0,7,1
3626455,2021,41899,4,COLEGIO SAN JORGE,8,BBIO,83,8304,LAJA,82,...,17,13,13119,MAIPÚ,0,0,0,0,7,k

In [3]:
df_2022 = pd.read_csv("df_2022_new.csv")
df_2022

/var/folders/xx/8ljg54gs66gdzlm3grgkg2vr0000gn/T/ipykernel_1436/2193284039.py:1: DtypeWarning: Columns (25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv("df_2022_new.csv")

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,EDAD_ALU,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,COD_RAMA,COD_MEN,ENS,DVR
0,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,40,15,15101,ARICA,410,41001,400,0,13,8
1,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,45,15,15101,ARICA,410,41001,400,0,13,k
2,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,18,15,15101,ARICA,410,41001,400,0,13,6
3,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,49,15,15101,ARICA,410,41001,400,0,13,5
4,2022,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,43,15,15101,ARICA,410,41001,400,0,13,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644543,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,77,10,10302,PUERTO OCTAY,0,0,0,0,9,8
3644544,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,57,10,10301,OSORNO,0,0,0,0,9,2
3644545,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,41,10,10301,OSORNO,0,0,0,0,9,6
3644546,2022,42081,6,ESCUELA HOSPITALARIA SANTA CRUZ,6,LGBO,63,6310,SANTA CRUZ,62,...,12,6,6201,PICHILEMU,0,0,0,0,3,7
3644547,2022,42081,6,ESCUELA HOSPITALARIA SANTA CRUZ,6,LGBO,63,6310,SANTA CRUZ,62,...,18,6,6310,SANTA CRUZ,0,0,0,0,7,8

In [42]:
Conectar_bases = pd.concat([df_2021, df_2022 ], axis=0)
Conectar_bases_SD= Conectar_bases.drop_duplicates()
display(len(Conectar_bases)-len(Conectar_bases_SD))

0

Debe responder las siguientes preguntas
1. Presentar, a trav´es de una tabla de doble entrada, la cantidad por sexo segun la dependencia del establecimiento. Indique la fecuencia absoluta y relativa (20 puntos).

In [5]:
tabla1 = df_2021.groupby("NOM_COM_ALU")["NOM_COM_ALU"].agg(["count"])
tabla1

                 count
NOM_COM_ALU
                 21946
ALGARROBO         2144
ALHUÉ             1452
ALTO BIOBÍO       1573
ALTO DEL CARMEN    862
...                ...
YUMBEL            3551
YUNGAY            3217
ZAPALLAR          1244
ÑIQUÉN            2013
ÑUÑOA            28476

[347 rows x 1 columns]

In [6]:

regiones_deseadas = ['AYSEN', 'ARAUC']
df_filtrado = df[df['regiones'].isin(regiones_deseadas)]

df_filtrado.to_csv('df_2021_filtrado.csv', index=False)

NameError: name 'df' is not defined

In [10]:
conectarbases = pd.concat([df_2021, df_2022 ], axis=0)
conectarbases

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,EDAD_ALU,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,COD_RAMA,COD_MEN,ENS,DVR
0,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,54,15,15101,ARICA,410,41001,400,0,13,8
1,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,24,15,15101,ARICA,410,41001,400,0,13,1
2,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,51,15,15101,ARICA,410,41001,400,0,13,6
3,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,43,1,1101,IQUIQUE,410,41001,400,0,13,8
4,2021,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,25,15,15101,ARICA,410,41001,400,0,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644543,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,77,10,10302,PUERTO OCTAY,0,0,0,0,9,8
3644544,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,57,10,10301,OSORNO,0,0,0,0,9,2
3644545,2022,42071,9,INSTITUTO DE EDUCACIÓN DE ADULTOS MONTAÑA NEVADA,10,LAGOS,103,10301,OSORNO,103,...,41,10,10301,OSORNO,0,0,0,0,9,6
3644546,2022,42081,6,ESCUELA HOSPITALARIA SANTA CRUZ,6,LGBO,63,6310,SANTA CRUZ,62,...,12,6,6201,PICHILEMU,0,0,0,0,3,7
3644547,2022,42081,6,ESCUELA HOSPITALARIA SANTA CRUZ,6,LGBO,63,6310,SANTA CRUZ,62,...,18,6,6310,SANTA CRUZ,0,0,0,0,7,8

In [ ]:
conectarbases[conectarbases["NOM_REG_RBD_A"].str.contains("AYSEN")|conectarbases["NOM_REG_RBD_A"].str.contains("ARAUC")]

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,EDAD_ALU,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_SEC,COD_ESPE,COD_RAMA,COD_MEN,ENS,DVR
995327,2021,5215,9,LICEO INDUSTRIAL B-5 ANGOL,9,ARAUC,92,9201,ANGOL,91,...,14,9,9201,ANGOL,0,0,0,0,5,4
995328,2021,5215,9,LICEO INDUSTRIAL B-5 ANGOL,9,ARAUC,92,9201,ANGOL,91,...,14,9,9201,ANGOL,0,0,0,0,5,2
995329,2021,5215,9,LICEO INDUSTRIAL B-5 ANGOL,9,ARAUC,92,9201,ANGOL,91,...,14,9,9201,ANGOL,0,0,0,0,5,5
995330,2021,5215,9,LICEO INDUSTRIAL B-5 ANGOL,9,ARAUC,92,9201,ANGOL,91,...,14,9,9201,ANGOL,0,0,0,0,5,1
995331,2021,5215,9,LICEO INDUSTRIAL B-5 ANGOL,9,ARAUC,92,9201,ANGOL,91,...,14,9,9201,ANGOL,0,0,0,0,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3643933,2022,41931,1,ESCUELA DE LENGUAJE RENACE,9,ARAUC,91,9115,PUCÓN,93,...,5,9,9115,PUCÓN,0,0,0,0,2,3
3643934,2022,41931,1,ESCUELA DE LENGUAJE RENACE,9,ARAUC,91,9115,PUCÓN,93,...,5,9,9115,PUCÓN,0,0,0,0,2,0
3643935,2022,41931,1,ESCUELA DE LENGUAJE RENACE,9,ARAUC,91,9115,PUCÓN,93,...,5,9,9115,PUCÓN,0,0,0,0,2,8
3643936,2022,41931,1,ESCUELA DE LENGUAJE RENACE,9,ARAUC,91,9115,PUCÓN,93,...,5,9,9115,PUCÓN,0,0,0,0,2,k
3643937,2022,41931,1,ESCUELA DE LENGUAJE RENACE,9,ARAUC,91,9115,PUCÓN,93,...,5,9,9115,PUCÓN,0,0,0,0,2,0

In [ ]:
base_2021[base_2021["NOM_REG_RBD_A"].str.contains("AYSEN")]

NameError: name 'base_2021' is not defined

In [ ]:
df_ejemplo1 = df_ejemplo.drop_duplicates()

NameError: name 'df_ejemplo' is not defined

In [ ]:
df_2021.agg.count()

AttributeError: 'function' object has no attribute 'count'

In [35]:
df_new = pd.DataFrame(df_2021)
duplicados = df_new["MRUN"].duplicated(keep = False)
N_duplicados = duplicados.sum()
N_duplicados

0

In [ ]:
df_12=df_2021["MRUN"].drop_duplicates()

NameError: name 'df_2021' is not defined

In [45]:
#5
df_comuna= conectarbases[conectarbases['NOM_COM_RBD']=='ANGOL']
df_comuna=df_comuna[['RURAL_RBD','NOM_RBD']].drop_duplicates()
df_comuna['RURAL_RBD'] = df_comuna['RURAL_RBD'].replace(0, 'URBANO')
df_comuna['RURAL_RBD'] = df_comuna['RURAL_RBD'].replace(1, 'RURAL')


tabla= df_comuna.groupby('RURAL_RBD')['NOM_RBD'].agg(["count"])
tabla

           count
RURAL_RBD
RURAL          6
URBANO        28